### ISSUE TITLE
啥时候能更新到1.12.2啊

### ISSUE THREAD

**Issue by KnightBlood** [UnknownStudio/ChinaCraft#21]
啥时候能更新到1.12.2啊 求更新

**Comment by trychen** [comment]
See [https://github.com/MinecraftPangu/Pangu](https://github.com/MinecraftPangu/Pangu)

**Comment by mouse0w0** [comment]
还有人关注这个项目吗？求人手啊

**Comment by RainyYC** [comment]
别问 问就是没有



------------------ 原始邮件 ------------------
发件人: "Mouse"<notifications@github.com>; 
发送时间: 2019年5月13日(星期一) 下午5:45
收件人: "UnknownStudio/ChinaCraft"<ChinaCraft@noreply.github.com>; 
抄送: "Subscribed"<subscribed@noreply.github.com>; 
主题: Re: [UnknownStudio/ChinaCraft] 啥时候能更新到1.12.2啊 (#21)




还有人关注这个项目吗？求人手啊
 
&mdash;

**Comment by mouse0w0** [comment]
整个华夏文明都撤项了，可以关注一下本团队正在开发的体素沙盒游戏引擎：https://github.com/UnknownDomainGame/UnknownDomain
