### ISSUE TITLE
Some bugs lately

### ISSUE THREAD

**Issue by mouse0w0** [UnknownStudio/ChinaCraft#4]
- [ ] 禅杖对不死生物的攻击力不够
- [x] 狼牙棒合成不正经
- [x] 桑树树苗删除熔炼合成
- [x] 作物种子没有获取方式
- [x] 生物没有生成
- [x] 木窗格合成方式不显示
- [x] 夜行衣白天可以隐身
- [x] 锡矿，大理石，玉原石不会生成

**Comment by trychen** [comment]
Fixed the NEI support of CCShapedIgnoreDamageRecipe
Added Spawn of EntityChinaZombie
e8a570b29eee0ba4478dc09764901612ab1ddd88

**Comment by trychen** [comment]
77002c4a6114ac3823b6ceb20e711ac8e01155e1

**Comment by mouse0w0** [comment]
Fixed ore generate
266c2af
